<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>UnVaultLauncher-CLI</AssemblyName>
    <RootNamespace>UnVault.CLI</RootNamespace>
    <Product>UnVault Launcher CLI</Product>
    <AssemblyTitle>UnVault Launcher CLI</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\UnVault.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.57.2" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.57.2" />
  </ItemGroup>

</Project>
